apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: myfirstapp
data:
  index.html: |
    <html>
    <h1>Yayy! Looks like you found my Kube webpage!</h1>
    </br>
    </html
    <h1>This web page is housed on a Pod running Nginx</h1>
    </html>