apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ap-ingress
  namespace: ap
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: "ap.mskube1.neueda.me"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: apache
            port:
              number: 80